const InvoiceDetailsActionTypes = {
  FETCH_INVOICES_DETAILS_START: 'FETCH_INVOICES_DETAILS_START',
  FETCH_INVOICES_DETAILS_SUCCESS: 'FETCH_INVOICES_DETAILS_SUCCESS',
  FETCH_INVOICES_DETAILS_FAILURE: 'FETCH_INVOICES_DETAILS_FAILURE',
};

export default InvoiceDetailsActionTypes;
