const InvoicesActionTypes = {
  FETCH_INVOICES_START: 'FETCH_INVOICES_START',
  FETCH_INVOICES_SUCCESS: 'FETCH_INVOICES_SUCCESS',
  FETCH_INVOICES_FAILURE: 'FETCH_INVOICES_FAILURE',
};

export default InvoicesActionTypes;
